name: Pulumi Destroy

on:
  workflow_dispatch: # Esto permite ejecutarlo manualmente

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Destroy Pulumi
        uses: pulumi/actions@v3
        with:
          command: destroy
          stack-name: LuisRiosAcloud/pulumi-project/dev
          work-dir: pulumi-project
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
