name: Pulumi CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
    # 1. Configurar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar Pulumi
    - name: Set up Pulumi
      uses: pulumi/actions@v3
      with:
        stack-name: dev
        work-dir: ./ # Cambia esto si el código de Pulumi está en un subdirectorio
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    # 3. Autenticar con Google Cloud
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    # 4. Configurar el proyecto y la región en GCP
    - name: Set Google Cloud Project and Region
      run: |
        gcloud config set project $GCP_PROJECT_ID
        gcloud config set compute/region $GCP_REGION
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_REGION: ${{ secrets.GCP_REGION }}

    # 5. Instalar dependencias (Go)
    - name: Install dependencies
      run: go mod tidy

    # 6. Desplegar infraestructura con Pulumi
    - name: Pulumi Up
      run: pulumi up --yes
