name: Pulumi CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      # Validar cambios con Pulumi Preview
      - name: Preview Pulumi Changes
        uses: pulumi/actions@v3
        with:
          command: preview
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      # Desplegar cambios con Pulumi Up
      - name: Deploy with Pulumi
        uses: pulumi/actions@v3
        with:
          command: up
          args: --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      # - uses: pulumi/actions@v6
      #   with:
      #     command: preview
      #     stack-name: Acloud-rip/dev
      #   env:
      #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      # - uses: pulumi/actions@v6
      #   with:
      #     command: up
      #     stack-name: Acloud-rip/dev
      #   env:
      #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
